=== SameerBramhecha/WTL_TE_SEM_VI/Assignment 3/external.dtd
<!ELEMENT employee (emp)>
<!ELEMENT emp (eid,empname,department,designation,salary)>
<!ELEMENT eid (#PCDATA)>
<!ELEMENT empname (#PCDATA)>
<!ELEMENT department (#PCDATA)>
<!ELEMENT designation (#PCDATA)>

=== SameerBramhecha/WTL_TE_SEM_VI/employee.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE employee SYSTEM "external.dtd">
<?xml-stylesheet type="text/xsl" href="xml_style.xsl"?>
<employee>
    <emp>
        <eid>1</eid>
        <empname>Santosh</empname>
        <department>Marketting</department>
        <designation>HR</designation>
        <salary>1000000</salary>
    </emp>
    <emp>
        <eid>2</eid>
        <empname>Sachin</empname>
        <department>Sales</department>
        <designation>Manager</designation>
        <salary>1500000</salary>
    </emp>
</employee>
